// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteServer(arg1) {
  return window['go']['service']['LocalStorageService']['DeleteServer'](arg1);
}

export function GetServerByID(arg1) {
  return window['go']['service']['LocalStorageService']['GetServerByID'](arg1);
}

export function GetServerList() {
  return window['go']['service']['LocalStorageService']['GetServerList']();
}

export function NewServer(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['service']['LocalStorageService']['NewServer'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SetCtx(arg1) {
  return window['go']['service']['LocalStorageService']['SetCtx'](arg1);
}

export function UpdateServer(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['service']['LocalStorageService']['UpdateServer'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
