// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {context} from '../models';

export function DeleteServer(arg1:number):Promise<void>;

export function GetServerByID(arg1:number):Promise<model.Server>;

export function GetServerList():Promise<Array<model.Server>>;

export function NewServer(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<model.Server>;

export function SetCtx(arg1:context.Context):Promise<void>;

export function UpdateServer(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;
