// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export function DeleteServer(id: number): $CancellablePromise<void> {
    return $Call.ByID(1689016721, id);
}

export function GetServerByID(id: number): $CancellablePromise<model$0.Server> {
    return $Call.ByID(327913448, id);
}

export function GetServerList(): $CancellablePromise<model$0.Server[] | null> {
    return $Call.ByID(1773391640);
}

export function NewServer(Type: number, Name: string, IP: string, User: string, PW: string, Comment: string): $CancellablePromise<model$0.Server> {
    return $Call.ByID(2538645466, Type, Name, IP, User, PW, Comment);
}

export function UpdateServer(id: number, Type: number, Name: string, IP: string, User: string, PW: string, Comment: string): $CancellablePromise<void> {
    return $Call.ByID(1911096523, id, Type, Name, IP, User, PW, Comment);
}
