// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export enum AuthMethod {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    Password = 0,
    SSHKEY = 1,
};

export interface Server {
    "ID": number;
    "Type": AuthMethod;
    "Name": string;
    "IP": string;
    "User": string;
    "PW": string;
    "Comment": string;
    "CreatedAt": number;
    "UpdatedAt": number;
}
